### ISSUE TITLE
File upload + download

### ISSUE THREAD

**Issue by Jasper-Nelligan** [J-Raymer/printlink3d#103]
STL files should be uploaded to Firebase and should be downloadable to the Printer

**Comment by mas393** [comment]
@Jasper-Nelligan fyi, with #111 I slightly changed the upload stl file process you added previously. Now, the upload is performed asynchronously after the thumbnail upload in the block below: 

https://github.com/J-Raymer/printlink3d/blob/ea27d1047914b9675369e9d93756fbada190bf09/src/routes/create.js#L84-L89

A job won't appear on the browse jobs page until the file finished uploading. In the backend, the file is now stored at `/print-files/${id}` where `id` is the firebase doc ref of a given job db entry. I changed the file path from `/print-files/${stl-file-name}` because there could be a collision between different files with the same name.

To download the stl file from the backend, you could use code similar to what I have for the thumbnail download here:
https://github.com/J-Raymer/printlink3d/blob/ea27d1047914b9675369e9d93756fbada190bf09/src/backend.js#L86
